name: help_page
description: 'Help page'
version: 0.0.1

environment:
  flutter: ^3.35.4
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  flutter_widget_from_html_core: ^0.17.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
