name: help_page
description: 'Help page'
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  package_info_plus: ^8.1.1
  url_launcher: ^6.3.1
  flutter_widget_from_html_core: ^0.15.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
