name: help_page
description: 'Help page'
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  flutter_widget_from_html_core: ^0.16.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
