name: help_page
description: 'Help page'
version: 0.0.1

environment:
  sdk: ^3.3.4
  flutter: ^3.19.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  flutter_widget_from_html_core: ^0.14.12

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
